'use strict'; // eslint-disable-line

function shouldExist(unitName) {
  return `
describe('${unitName}', () => {
  // Auto-generated by LazySpec
  // TODO replace with a better spec
  it('should exist', () => {
    expect(${unitName}).toBeTruthy();
  });
});
`;
}

function specUnit(moduleInfo) {
  const parts = [];

  if (moduleInfo.exportsDefault) {
    parts.push(shouldExist(moduleInfo.moduleName));
  }

  for (const namedExport of moduleInfo.namedExportNames) {
    parts.push(shouldExist(namedExport));
  }

  return parts.join('\n');
}

module.exports = specUnit;
